name: Build and Upload to JFrog

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up JDK 12
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '12'

    - name: Run Tests
      run: mvn test

    - name: Deploy to Jfrog
      env:
        USER: ${{ secrets.CI_JFROG_USERNAME }}
        PASS: ${{ secrets.CI_JFROG_PASSWORD }}
      run:   mvn deploy --settings settings.xml -Dmaven.test.skip=true -Dmaven.javadoc.skip=true -Dgpg.skip -P jfrog  -Denv.CI_JFROG_USERNAME=${USER} -Denv.CI_JFROG_PASSWORD=${PASS}
