name: Build and Upload to JFrog

on:
  push:
    tags:
      - '*'

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 12
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '12'

      - name: Run Tests
        run: mvn test

  deploy:
    needs: tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 12
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '12'

      - name: Get Tag Name
        id: tag_name
        run: echo "TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT

      - name: Deploy to Jfrog
        env:
          USER: ${{ secrets.CI_JFROG_USERNAME }}
          PASS: ${{ secrets.CI_JFROG_PASSWORD }}
        run: mvn deploy --settings settings.xml -Dversion=${{  steps.tag_name.outputs.TAG }} -Dmaven.test.skip=true -Dmaven.javadoc.skip=true -Dgpg.skip -P jfrog -Denv.CI_JFROG_USERNAME=${USER} -Denv.CI_JFROG_PASSWORD=${PASS}

      - name: Deploy to Maven
        env:
          PHRASE: ${{ secrets.CI_MAVEN_GPG_PHRASE }}
        run: mvn deploy --settings settings.xml -Dversion=${{  steps.tag_name.outputs.TAG }} -Dgpg.passphrase=${PHRASE}