name: Build and Upload to JFrog

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up JDK 12
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '12'

    - name: Run Tests
      run: mvn test

    - name: Build with Maven
      run:  mvn clean install -Dmaven.test.skip=true -Dmaven.javadoc.skip=true

  upload-to-jfrog:
    runs-on: self-hosted

    needs: build

    steps:
    - name: Get Tag Name
      id: tag_name
      run: echo "::set-output name=tag::$(git describe --tags --abbrev=0)"

    - name: Upload to JFrog
      uses: jfrog/github-actions/artifactory-upload@v1
      with:
        username: deploy
        password: RT3409dp!
        server-url: 'http://jfrog.sitrack.io'  # Cambia esto según tu instancia de JFrog
        repository: 'shelbyville'  # Cambia esto según tu repositorio en JFrog
        package: "com/github/javaito/hcjf/${{ steps.tag_name.outputs.tag }}"  # Incorpora el tag en el nombre del paquete
        spec: 'target/*.jar'

